spring.main.allow-bean-definition-overriding=true
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=VanMos;integratedSecurity=false;encrypt=false;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=Leo199497@
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none